#!/usr/bin/env python
import PySimpleGUI as sg
import subprocess
import youtube_dl
import os
import threading
import math
import validators

class Syd:
    _APP_NAME = 'syd-music'
    #events
    _EVENT_BEGIN = 'begin'
    _EVENT_PROGRESS = 'dl_progress'
    _EVENT_CONVERT_BEGIN = 'convert_begin'
    _EVENT_CONVERT_END = 'convert_end'

    def __init__(self):
        #GUI
        sg.theme('LightGreen')
        layout = [  
            [sg.Text('YouTube link')],
            [sg.InputText(key='url')], 
            [sg.Button('Download MP3', key='dl', bind_return_key=True), sg.Button('View downloaded songs', key='view')], 
            [sg.Text(key='status', size=(24,1))]
        ]
        self._window = sg.Window('syd-music', layout)
        #YoutubeDL
        self._DOWNLOAD_PATH = '{}/Music/{}/'.format(os.environ['HOME'], self._APP_NAME)
        opts = {
            'outtmpl': '{}%(title)s.%(ext)s'.format(self._DOWNLOAD_PATH),
            'format': 'bestaudio/best',
            'ignoreerrors': 'true',
            'progress_hooks': [self._dl_progress_hook],
            'postprocessors': [{
                'key': 'FFmpegExtractAudio',
                'preferredcodec': 'mp3',
                'preferredquality': '128',
            }],
        }
        self._ytdl = youtube_dl.YoutubeDL(opts)

    def start(self):
        while True: 
            event, values = self._window.read()
            if event == 'dl':
                self._download(values['url'])
            if event == self._EVENT_BEGIN:
                self._dl_enabled(False)
                self._status('Gathering info…')
            if event == self._EVENT_PROGRESS:
                perc = values[event]
                self._status('Downloading: {}'.format(perc))
            if event == self._EVENT_CONVERT_BEGIN: 
                self._status('Converting to MP3…')
            if event == self._EVENT_CONVERT_END:
                self._status('Done!')
                self._dl_enabled()
            if event == 'view':
                subprocess.Popen(['xdg-open', self._DOWNLOAD_PATH])
            if event == sg.WINDOW_CLOSED:
                break

        self._window.close()

    def _download(self, url):
        if not validators.url(url): 
            self._status('That\'s not a link.')
        elif not '//www.youtube.com/watch?v=' in url:
            self._status('That\'s not a YouTube link.')
        else:
            threading.Thread(
                target=self._dl_worker, 
                args=(url,), 
                daemon=True
            ).start()

    def _event(self, key, value=any):
        self._window.write_event_value(key, value)

    def _status(self, msg):
        self._window['status'].update(msg)

    def _dl_enabled(self, enabled=True):
        self._window['dl'].update(disabled=not enabled)

    def _dl_worker(self, url):
        self._event(self._EVENT_BEGIN)
        self._ytdl.download([url])
        self._event(self._EVENT_CONVERT_END)

    def _dl_progress_hook(self, prog):
        status = prog['status']
        if status == 'downloading':
            self._event(self._EVENT_PROGRESS, prog['_percent_str'])
        if status == 'finished':
            self._event(self._EVENT_CONVERT_BEGIN)

if __name__ == '__main__':
    Syd().start()